### ISSUE TITLE
Send function hangs without error

### ISSUE THREAD

**Issue by Alko89** [BitskiCo/bitski-node#17]
I'm trying to send a transaction using Bitski provider in node.js. I have created the API key and creadentials in the dashboard and created a new provider.

The problem occurs when I try to send a transaction. The function executes fine and returns the transaction id in `then` clause (which is also visible in etherscan). After that the code stops executing without throwing an error.

This is the code I'm trying to execute (basically I'm trying to write arbitrary data in the data field). I'm testing on rinkeby network and running node v12.11.1.
```
const bitskiOptions = {
  network: 'rinkeby',
  credentials: {
    id: 'ID',
    secret: 'SECRET'
  }
};

const provider = Bitski.getProvider('API KEY', bitskiOptions);

let params = [{
  from: "0x9b9a9e873f1aba4f676b23cc382f4c51c479d738",
  to: "0x9b9a9e873f1aba4f676b23cc382f4c51c479d738",
  gas: "0x6208",
  gasPrice: "0x4A817C800",
  value: "0x0",
  data: data
}]

provider.send('eth_sendTransaction', params)
  .then((res) => {
    console.log(res);
  })
  .catch((err) => {
    console.log(err);
  });
```

**Comment by ptescher** [comment]
@Alko89 sounds like the code is working as intended. Our API continues to monitor the blockchain for transactions results, but you have not acted on anything except the receipt so you only see that.

If you want the process to exit once you have sent the transaction you can pass `disableBlockTracking: true` in your options. If you want further information on your transaction I suggest initializing Web3 and using its sendTransaction to monitor the progress.

**Comment by Alko89** [comment]
@ptescher thanks, `disableBlockTracking` did help. I have also tried using the provider with web3x and noticed the same behavior. In both cases the flag works as intended.
